version: '3'
services:

  couchbase:
    image: couchbase:community-6.0.0
    container_name: couchbase
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    networks:
      - elastic-couchbase
      
networks:
  elastic-couchbase: