version: '3'
services:

  couchbase:
    image: couchbase:community-6.0.0
    container_name: db
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    networks:
      - elastic-couchbase

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: search
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      # Elasticsearch uses node.name as a human readable identifier for a particular instance of Elasticsearch so it is included in the response of many APIs.
      # It defaults to the hostname that the machine has when Elasticsearch starts but can be configured explicitly in elasticsearch.yml
      - node.name=search
      # A node can only join a cluster when it shares its cluster.name with all the other nodes in the cluster.
      # The default name is elasticsearch, but you should change it to an appropriate name which describes the purpose of the cluster.
      - cluster.name=es-docker-cluster
      # By default, Elasticsearch binds to loopback addresses only — e.g. 127.0.0.1 and [::1].
      #- network.host=127.0.0.1
      # Automatic index creation is controlled by the action.auto_create_index setting.
      # This setting defaults to true, which allows any index to be created automatically.
      # More information: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-index_.html
      - action.auto_create_index=true
      # This is sufficient to run a single development node on a server.
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - elastic-couchbase

networks:
  elastic-couchbase: