version: '3.7'
services:

  couchbase:
    image: couchbase:latest
    container_name: db
    ports:
      - 8091:8091
      - 8092:8092
      - 8093:8093
      - 11210:11210
    environment:
      CB_USER: ${CB_USER}
      CB_PWD: ${CB_PWD}
      CB_BUCKET: ${CB_BUCKET}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://${CB_USER}:${CB_PWD}@127.0.0.1:8091/pools/default/buckets/${CB_BUCKET}"]
      interval: 1s
      timeout: 3s
      retries: 50
    networks:
      - elastic-couchbase

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.1
    container_name: search
    ports:
      - 9200:9200
      - 9300:9300
      - 9600:9600 # Required for Performance Analyzer
    environment:
      - node.name=${ES_NODE}
      - cluster.name=${ES_CLUSTER}
      - action.auto_create_index=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - ES_USER=${ES_USER}
      - ES_PWD=${ES_PWD}
      - ES_INDEX=${ES_INDEX}
    ulimits:
      memlock:
        soft: -1
        hard: -1
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail 127.0.0.1:9200/_cluster/health || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - elastic-couchbase

networks:
  elastic-couchbase: