# Setting Spring default profile (it will look for application-{dev}.yml file)
spring:
  profiles:
    active: dev

  # Couchbase configuration
  couchbase:
    username: ${CB_USER}
    password: ${CB_PWD}
    bootstrap-hosts:
      - 127.0.0.1
    bucket:
      name: ${CB_BUCKET}

  data:
    couchbase:
      auto-index: true
      repositories:
        type: AUTO

    elasticsearch:
      cluster-name: ${ES_CLUSTER}
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: false

  elasticsearch:
    rest:
      uris:
        - http://127.0.0.1:9200

# Common properties for all profiles
logging:
  level:
    web: INFO
