# Setting Spring default profile (it will look for application-{dev}.yml file)
spring:
  profiles:
    active: dev

  # Couchbase configuration
  couchbase:
    username: ${COUCHBASE_ADMIN_USER}
    password: ${COUCHBASE_ADMIN_PWD}
    bootstrap-hosts:
      - 127.0.0.1
    bucket:
      name: ${BUCKET_NAME}

  data:
    couchbase:
      auto-index: true
      repositories:
        type: AUTO

    elasticsearch:
      cluster-name: ${ELASTIC_CLUSTER_NAME}
      cluster-nodes: 127.0.0.1:9300
      repositories:
        enabled: false

  elasticsearch:
    rest:
      uris:
        - http://127.0.0.1:9200

nats:
  spring:
    server: nats://localhost:4222

# Common properties for all profiles
logging:
  level:
    web: INFO
